# This is an example neoforge.mods.toml file. It contains the data relating to the loading mods.
# The overall format is standard TOML format, v0.5.0.

# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="javafml" #mandatory

# A version range to match for said mod loader - for regular FML @Mod it will be the FML version.
loaderVersion="${loader_version_range}" #mandatory

# The license for you mod.
license="${mod_license}"

# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory
# The modid of the mod
modId="${mod_id}" #mandatory

# The version number of the mod
version="${mod_version}" #mandatory

# A display name for the mod
displayName="${mod_name}" #mandatory

# A file name (in the root of the mod JAR) containing a logo for display
# logoFile="endergy_resurrected.png" #optional

# The description text for the mod (multi line!) (#mandatory)
description='''
    Port of Ender IO Addon to 1.21.1 NeoForge.
    Includes new conduits and grinding balls.
    '''

# 1. NeoForge 依赖
[[dependencies.${mod_id}]] #optional
modId="neoforge" #mandatory
type="required" #mandatory
versionRange="[${neo_version},)" #mandatory
ordering="NONE"
side="BOTH"

# 2. Minecraft 依赖
[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

# 3. Ender IO 依赖
[[dependencies.${mod_id}]]
modId="enderio"       # 必须匹配 Ender IO 的 modId
type="required"       # 必须依赖
versionRange="[7.0.0-alpha,8.0.7-alpha]"
ordering="AFTER"      # 确保在 Ender IO 之后加载
side="BOTH"
reason="Re:endergy requires Ender IO version 7.0.0 to 8.0.7."
